### ISSUE TITLE
Unable to install on MS 365 Apps for enterprise

### ISSUE THREAD

**Issue by RaenonX** [wakatime/office-wakatime#1]
I am using Office 365 because my school account has it. The plugin I tried to install is for Excel.

Despite I ran `ExcelSetup.msi` and it says "successfully installed," nothing popped up for me to enter the API key.
- I reran the msi file, and it gives the repairing and removing options, which I think it's an indicator that the system considers it as installed.

I tried to manually install the plugin via the Excel settings, but it gives **not a valid add-in.**
- Via `Options > Add-ins > Manage > COM Add-ins`

**Comment by yihuajack** [comment]
Same problem on Microsoft Office 2019 and Microsoft 365 Family

**Comment by ZhixuNi** [comment]
Hi @RaenonX @yihuajack !

I've got a solution to make it work.
You need to manually use the `Registry Editor` to edit somethings:
I think this is due to some issues, the WakaTime msi installer failed to generate some keys.
According to MS official website:
https://docs.microsoft.com/en-us/visualstudio/vsto/registry-entries-for-vsto-add-ins?view=vs-2019

Following keys have to be created under:
`Computer\HKEY_CURRENT_USER\SOFTWARE\Microsoft\Office\Word\Addins`

The most important is the `Manifest` vale:
for me the value is:
`file:///C:\Program Files (x86)\WakaTime\WordWakaTimeAddin\WordWakaTimeAddin.vsto|vstolocal`

**You have to find your own path to WordWakaTimeAddin.vsto file.**
![Waka_reg_01](https://user-images.githubusercontent.com/9975812/103301301-61bb0000-4a01-11eb-94dd-5239eaafc339.png)

*Edited:*
Manifest for Excel:
`file:///C:\Program Files (x86)\WakaTime\ExcelWakaTimeAddin\ExcelWakaTimeAddin.vsto|vstolocal`

![Waka_Excel](https://user-images.githubusercontent.com/9975812/103315162-17e41100-4a25-11eb-99f2-4bd31ccd9e02.png)

Manifest for PowerPoint:
`file:///C:\Program Files (x86)\WakaTime\PowerPointWakaTimeAddin\PowerPointWakaTimeAddin.vsto|vstolocal`

![Waka_PowerPoint](https://user-images.githubusercontent.com/9975812/103315169-1b779800-4a25-11eb-8367-ee4020fbeab8.png)

Then close regedit and start word you may asked to trust WakaTime and install the plugin.
Then you might get one more key in regedit and two times WakaTime COM addin in Word:
![Waka_reg](https://user-images.githubusercontent.com/9975812/103301565-f7568f80-4a01-11eb-83c2-824f5ad7ddb8.png)

Anyway, I disabled one of it and it works now:
![Waka_reg_03](https://user-images.githubusercontent.com/9975812/103301606-0b01f600-4a02-11eb-9b68-7a5a6799cf76.png)

![Waka_reg_04](https://user-images.githubusercontent.com/9975812/103301635-16edb800-4a02-11eb-8939-3a8b694b0b9f.png)

![Waka_reg_06](https://user-images.githubusercontent.com/9975812/103316742-b96d6180-4a29-11eb-8faf-0f5c3ae19418.png)

If the value:
`file:///C:\Program Files (x86)\WakaTime\WordWakaTimeAddin\WordWakaTimeAddin.vsto|vstolocal` not working, try:
`file:///C:\Program Files (x86)\WakaTime\WordWakaTimeAddin\WordWakaTimeAddin.vsto` which without `|vstolocal`

Hope this solution works for you as well!

**Comment by yihuajack** [comment]
@ZhixuNi Thanks for your solution! It works for me. Nevertheless, it seems that things are different for Excel and PowerPoint. Is there any way to solve this issue for Excel and PowerPoint?

**Comment by ZhixuNi** [comment]
@yihuajack 
Hi!
Good to know that it works for you as well!
I added similar keys for Excel and PowerPoint and they work fine for me:

Manifest for Excel:
`file:///C:\Program Files (x86)\WakaTime\ExcelWakaTimeAddin\ExcelWakaTimeAddin.vsto|vstolocal`

Manifest for PowerPoint:
`file:///C:\Program Files (x86)\WakaTime\PowerPointWakaTimeAddin\PowerPointWakaTimeAddin.vsto|vstolocal`

Actually you do not need to add keys under `AddinsData`, since it will be created automatically when you start Excel/PowerPoint/Word. It only count how many times this plugin got launched.

![Waka_Excel](https://user-images.githubusercontent.com/9975812/103315162-17e41100-4a25-11eb-99f2-4bd31ccd9e02.png)

![Waka_PowerPoint](https://user-images.githubusercontent.com/9975812/103315169-1b779800-4a25-11eb-8367-ee4020fbeab8.png)

**Comment by RaenonX** [comment]
@ZhixuNi Works like a charm, thanks!

**Comment by kmedri** [comment]
Hi, I have tried all of this and still cannot seem to get a connection working. It does not appear in my plugin status page. The same is happening for Excel. I have logging in Word however not sure what I should be looking for.
I get no errors and I can see the WakaTime option in the menu bar. The API key is added into the options ok.

**Comment by MicheleRabesco** [comment]
Hi, I tried all of the above but when I enter my API key I get this pop-up:
![Immagine 2023-01-19 204701](https://user-images.githubusercontent.com/64683609/213545020-d5ee64af-a637-43b5-970b-301be69eb868.jpg)

I noticed that when I try to enter my own API key I can't write the last 5 digits:
![image](https://user-images.githubusercontent.com/64683609/213546350-378492cf-76be-488a-9135-9eaf3634a907.png)

Is there a place where I can set my API key other than there?
Thanks

**Comment by yihuajack** [comment]
@MicheleRabesco This is because you indeed entered an invalid API key. The API key are all hex numbers

**Comment by kmedri** [comment]
@MicheleRabesco If you remove the waka_ from the beginning of the key it should work.

**Comment by MicheleRabesco** [comment]
> @MicheleRabesco If you remove the waka_ from the beginning of the key it should work.

Okay, this worked for me, I didn't know that. Thanks a lot!
